// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadFinished = { key: string, };

export type DownloadProgress = { key: string, downloaded: number, speed: number, };

export type DownloadStart = { key: string, totalSize: number, };

export type Engine = { key: string, version: string, flavor: string, dotnet: boolean, path: string, releaseDate: number, lastUsed: number, };

export type Error = "newsFeedFetch" | "newsFeedDecoding" | "newsFeedParsing" | "projectFolderDoesntExist" | "projectFolderIsNotGodot" | "projectAlreadyAdded" | "projectUnsupportedGodot" | "projectInvalidFile" | "versionsFetch" | "versionsDecoding" | "releaseApiFetch" | "platformNameNotFound" | "buildNotFound" | "engineNotFound";

export type NewsFeed = { online: boolean, items: Array<NewsItem>, lastChecked: number, lastUpdate: number, };

export type NewsItem = { id: string, title: string, link: string, description: string, category: string, creator: string, image: string, pubDate: string, };

export type Project = { name: string, path: string, icon: string, favorite: boolean, dotnet: boolean, lastOpened: number, engineVersion: string, engineUse: string, };

export type ProjectInfo = { name: string, path: string, dotnet: boolean, version: string, icon: string, };

export type Version = { key: string, name: string, flavor: string, group: string, releaseDate: string, releaseNotes: string, };
